### ISSUE TITLE
Getting a BSOD crashes the game

### ISSUE THREAD

**Issue by zai-tm** [BurningInfern0/ProgressCLI95#3]
![image](https://user-images.githubusercontent.com/74737630/147863178-368f6ef0-ab51-43b4-9c43-5971d9ccce06.png)

**Comment by BurningInfern0** [comment]
It appears I missed a variable that I needed to rename. This shouldn't take long.

**Comment by BurningInfern0** [comment]
The issue has been fixed and has been committed into the main branch.
